version: "3"
services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - database
  database:
    image: "mongo"
    container_name: "mongo_database_flask"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
